#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutForm(object):
    def setupUi(self, AboutForm):
        AboutForm.setObjectName("AboutForm")
        AboutForm.resize(504, 287)
        self.centralwidget = QtWidgets.QWidget(AboutForm)
        self.centralwidget.setObjectName("centralwidget")
        self.OKButton = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.OKButton.setGeometry(QtCore.QRect(10, 250, 486, 31))
        self.OKButton.setOrientation(QtCore.Qt.Horizontal)
        self.OKButton.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.OKButton.setCenterButtons(True)
        self.OKButton.setObjectName("OKButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.textEdit = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        # AboutForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(AboutForm)
        QtCore.QMetaObject.connectSlotsByName(AboutForm)

    def retranslateUi(self, AboutForm):
        _translate = QtCore.QCoreApplication.translate
        AboutForm.setWindowTitle(_translate("AboutForm", "About"))

    # def __init__(self):
    #     super().__init__()

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     AboutForm = QtWidgets.QMainWindow()
#     ui = Ui_AboutForm()
#     ui.setupUi(AboutForm)
#     AboutForm.show()
#     sys.exit(app.exec_())
