# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configcolor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(376, 161)
        self.centralwidget = QtWidgets.QWidget(ConfigForm)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 375, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.colorTab = QtWidgets.QWidget()
        self.colorTab.setObjectName("colorTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.colorTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_red = QtWidgets.QTextBrowser(self.colorTab)
        self.textBrowser_red.setGeometry(QtCore.QRect(310, 10, 51, 21))
        self.textBrowser_red.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.textBrowser_red.setLineWidth(0)
        self.textBrowser_red.setMidLineWidth(0)
        self.textBrowser_red.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_red.setReadOnly(False)
        self.textBrowser_red.setObjectName("textBrowser_red")
        self.horizontalSlider_blue = QtWidgets.QSlider(self.colorTab)
        self.horizontalSlider_blue.setGeometry(QtCore.QRect(50, 77, 255, 13))
        self.horizontalSlider_blue.setMaximum(255)
        self.horizontalSlider_blue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_blue.setObjectName("horizontalSlider_blue")
        self.label_blue = QtWidgets.QLabel(self.colorTab)
        self.label_blue.setGeometry(QtCore.QRect(17, 72, 31, 21))
        self.label_blue.setObjectName("label_blue")
        self.horizontalSlider_green = QtWidgets.QSlider(self.colorTab)
        self.horizontalSlider_green.setGeometry(QtCore.QRect(50, 46, 255, 13))
        self.horizontalSlider_green.setMaximum(255)
        self.horizontalSlider_green.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_green.setObjectName("horizontalSlider_green")
        self.textBrowser_blue = QtWidgets.QTextBrowser(self.colorTab)
        self.textBrowser_blue.setGeometry(QtCore.QRect(310, 72, 51, 21))
        self.textBrowser_blue.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.textBrowser_blue.setLineWidth(0)
        self.textBrowser_blue.setReadOnly(False)
        self.textBrowser_blue.setObjectName("textBrowser_blue")
        self.textBrowser_green = QtWidgets.QTextBrowser(self.colorTab)
        self.textBrowser_green.setGeometry(QtCore.QRect(310, 42, 51, 21))
        self.textBrowser_green.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.textBrowser_green.setLineWidth(0)
        self.textBrowser_green.setMidLineWidth(0)
        self.textBrowser_green.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_green.setTabChangesFocus(False)
        self.textBrowser_green.setReadOnly(False)
        self.textBrowser_green.setObjectName("textBrowser_green")
        self.label_green = QtWidgets.QLabel(self.colorTab)
        self.label_green.setGeometry(QtCore.QRect(7, 42, 40, 21))
        self.label_green.setObjectName("label_green")
        self.horizontalSlider_red = QtWidgets.QSlider(self.colorTab)
        self.horizontalSlider_red.setGeometry(QtCore.QRect(50, 14, 255, 13))
        self.horizontalSlider_red.setMaximum(255)
        self.horizontalSlider_red.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_red.setObjectName("horizontalSlider_red")
        self.ACOButton = QtWidgets.QDialogButtonBox(self.colorTab)
        self.ACOButton.setGeometry(QtCore.QRect(30, 100, 331, 28))
        self.ACOButton.setOrientation(QtCore.Qt.Horizontal)
        self.ACOButton.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ACOButton.setObjectName("ACOButton")
        self.label_red = QtWidgets.QLabel(self.colorTab)
        self.label_red.setGeometry(QtCore.QRect(19, 10, 26, 21))
        self.label_red.setObjectName("label_red")
        self.tabWidget.addTab(self.colorTab, "")
        ConfigForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfigForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "Configure"))
        self.label_blue.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\" font-size:10pt; color:#0336ff;\">Blue:</span></p></body></html>"))
        self.label_green.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\" font-size:10pt; color:#018786;\">Green:</span></p></body></html>"))
        self.label_red.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\" font-size:10pt; color:#b00020;\">Red:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.colorTab), _translate("ConfigForm", "Colors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigForm = QtWidgets.QMainWindow()
    ui = Ui_ConfigForm()
    ui.setupUi(ConfigForm)
    ConfigForm.show()
    sys.exit(app.exec_())
