# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigForm(object):
    def setupUi(self, ConfigForm):
        ConfigForm.setObjectName("ConfigForm")
        ConfigForm.resize(591, 298)
        self.centralwidget = QtWidgets.QWidget(ConfigForm)
        self.centralwidget.setObjectName("centralwidget")
        self.ConfigButton = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.ConfigButton.setGeometry(QtCore.QRect(10, 270, 571, 28))
        self.ConfigButton.setOrientation(QtCore.Qt.Horizontal)
        self.ConfigButton.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ConfigButton.setObjectName("ConfigButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.pixycolorTab = QtWidgets.QWidget()
        self.pixycolorTab.setObjectName("pixycolorTab")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.pixycolorTab)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.pixycolorLayout = QtWidgets.QGridLayout()
        self.pixycolorLayout.setObjectName("pixycolorLayout")
        self.gridLayout_1.addLayout(self.pixycolorLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pixycolorTab, "")
        self.pixyTab = QtWidgets.QWidget()
        self.pixyTab.setObjectName("pixyTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pixyTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pixyLayout = QtWidgets.QGridLayout()
        self.pixyLayout.setObjectName("pixyLayout")
        self.gridLayout_2.addLayout(self.pixyLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pixyTab, "")
        self.pixymonTab = QtWidgets.QWidget()
        self.pixymonTab.setObjectName("pixymonTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pixymonTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pixymonLayout = QtWidgets.QGridLayout()
        self.pixymonLayout.setObjectName("pixymonLayout")
        self.gridLayout_3.addLayout(self.pixymonLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pixymonTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_blue = QtWidgets.QLabel(self.centralwidget)
        self.label_blue.setGeometry(QtCore.QRect(37, 110, 31, 21))
        self.label_blue.setObjectName("label_blue")
        self.textBrowser_red = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_red.setGeometry(QtCore.QRect(330, 48, 51, 21))
        self.textBrowser_red.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.textBrowser_red.setLineWidth(0)
        self.textBrowser_red.setMidLineWidth(0)
        self.textBrowser_red.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textBrowser_red.setReadOnly(False)
        self.textBrowser_red.setObjectName("textBrowser_red")
        self.textBrowser_green = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_green.setGeometry(QtCore.QRect(330, 80, 51, 21))
        self.textBrowser_green.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.textBrowser_green.setLineWidth(0)
        self.textBrowser_green.setMidLineWidth(0)
        self.textBrowser_green.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textBrowser_green.setTabChangesFocus(False)
        self.textBrowser_green.setReadOnly(False)
        self.textBrowser_green.setObjectName("textBrowser_green")
        self.horizontalSlider_green = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_green.setGeometry(QtCore.QRect(70, 84, 255, 13))
        self.horizontalSlider_green.setMaximum(255)
        self.horizontalSlider_green.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_green.setObjectName("horizontalSlider_green")
        self.horizontalSlider_red = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_red.setGeometry(QtCore.QRect(70, 52, 255, 13))
        self.horizontalSlider_red.setMaximum(255)
        self.horizontalSlider_red.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_red.setObjectName("horizontalSlider_red")
        self.horizontalSlider_blue = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_blue.setGeometry(QtCore.QRect(70, 115, 255, 13))
        self.horizontalSlider_blue.setMaximum(255)
        self.horizontalSlider_blue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_blue.setObjectName("horizontalSlider_blue")
        self.label_red = QtWidgets.QLabel(self.centralwidget)
        self.label_red.setGeometry(QtCore.QRect(39, 48, 26, 21))
        self.label_red.setObjectName("label_red")
        self.label_green = QtWidgets.QLabel(self.centralwidget)
        self.label_green.setGeometry(QtCore.QRect(27, 80, 40, 21))
        self.label_green.setObjectName("label_green")
        self.textBrowser_blue = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_blue.setGeometry(QtCore.QRect(330, 110, 51, 21))
        self.textBrowser_blue.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.textBrowser_blue.setLineWidth(0)
        self.textBrowser_blue.setReadOnly(False)
        self.textBrowser_blue.setObjectName("textBrowser_blue")
        # ConfigForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfigForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ConfigForm)

    def retranslateUi(self, ConfigForm):
        _translate = QtCore.QCoreApplication.translate
        ConfigForm.setWindowTitle(_translate("ConfigForm", "Configure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pixycolorTab), _translate("ConfigForm", "Colors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pixyTab), _translate("ConfigForm", "Parameters (saved on Pixy)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pixymonTab), _translate("ConfigForm", "Parameters (saved on computer)"))
        self.label_blue.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\"\n"
"                        font-size:10pt;\n"
"                        color:#0336ff;\">Blue:</span></p></body></html>"))
        self.label_red.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\"\n"
"                        font-size:10pt;\n"
"                        color:#b00020;\">Red:</span></p></body></html>"))
        self.label_green.setText(_translate("ConfigForm", "<html><head/><body><p><span style=\"\n"
"                        font-size:10pt;\n"
"                        color:#018786;\">Green:</span></p></body></html>"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ConfigForm = QtWidgets.QMainWindow()
#     ui = Ui_ConfigForm()
#     ui.setupUi(ConfigForm)
#     ConfigForm.show()
#     sys.exit(app.exec_())
