#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import PyQt5
import time
import datetime
import numpy as np
import usb

# import config
import config_ui
# import detect
# import main_ui
# import about_ui

# import PyQt5.Qt as Qt
import PyQt5.QtCore as QtCore
import PyQt5.QtDBus as QtDBus
import PyQt5.QtGui as QtGui
import PyQt5.QtWidgets as QtWidgets
# import PyQt5.QtNetwork as QtNetwork
# import PyQt5.QtXmlPatterns as QtXmlPatterns
# from PyQt5 import *

from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QFileDialog, QInputDialog, QGraphicsRectItem, QGraphicsScene, QMessageBox, QMainWindow, QToolTip, QPushButton, QLineEdit, QDialog, QHBoxLayout, QVBoxLayout, QSlider, QCheckBox, QGridLayout, QGroupBox, QRadioButton, QMenu, QTextEdit
from PyQt5.QtCore import pyqtSlot, Qt
from PyQt5.QtGui import QIcon, QFont, QImage, QPixmap
from PyQt5.uic import loadUi

from config_ui import Ui_ConfigForm

class configForm(QWidget):
    
    def __init__(self, parent=None):
        super(configForm, self).__init__(parent)
        self.title = "Config Slider"
        self.top = 200
        self.left = 500
        self.width = 400
        self.height = 300
        self.setWindowIcon(QtGui.QIcon("./images/logo.png"))
        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)

        # self.createGridLayout()
        self.grid_layout = QGridLayout()
        self.setLayout(self.grid_layout)


        self.grid_layout.addWidget(self.createRedSlider(), 0, 1, 1, 3)


        self.grid_layout.addWidget(self.createGreenSlider(), 1, 1, 1, 3)


        self.grid_layout.addWidget(self.createBlueSlider(), 2, 1, 1, 3)
        # self.createGreenSlider()
        # self.createBlueSlider()

    def createGridLayout(self):
        self.horizontalGroupBox = QGroupBox("Grid")
        layout = QGridLayout()
        
        layout.addWidget(self.createRedSlider(),1,0)
        layout.addWidget(self.createGreenSlider(),1,1)
        layout.addWidget(self.createBlueSlider(),2,0)
        
        self.horizontalGroupBox.setLayout(layout)

    def createRedSlider(self):
        hbox = QHBoxLayout()
        self.slider = QSlider()
        self.slider.setOrientation(Qt.Vertical)
        self.slider.setTickPosition(QSlider.TicksBelow)
        
        self.slider.setMinimum(0)
        self.slider.setMaximum(255)
        # self.slider.setRange(0, 255)
        self.slider.setPageStep(10)
        self.slider.valueChanged.connect(self.changedValue)

        self.label = QLabel("Red")
        self.label.setFont(QtGui.QFont("Sanserif", 15))
        self.label.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.label.setStyleSheet('QLabel { background: #FF0000; border-radius: 3px;}')

        hbox.addWidget(self.slider)
        hbox.addWidget(self.label)
        hbox.addStretch()
        hbox.addSpacing(15)
        self.setLayout(hbox)

    def createGreenSlider(self):
        hbox = QHBoxLayout()
        self.slider = QSlider()
        self.slider.setOrientation(Qt.Vertical)
        self.slider.setTickPosition(QSlider.TicksBelow)
        
        # self.slider.setMinimum(0)
        # self.slider.setMaximum(255)
        self.slider.setRange(0, 255)
        self.slider.setPageStep(5)
        self.slider.valueChanged.connect(self.changedValue)

        self.label = QLabel("Green")
        self.label.setFont(QtGui.QFont("Sanserif", 15))
        self.label.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.label.setStyleSheet('QLabel { background: #00FF00; border-radius: 3px;}')

        hbox.addWidget(self.slider)
        hbox.addWidget(self.label)
        hbox.addStretch()
        hbox.addSpacing(35)
        self.setLayout(hbox)

    def createBlueSlider(self):
        hbox = QHBoxLayout()
        self.slider = QSlider()
        self.slider.setOrientation(Qt.Vertical)
        self.slider.setTickPosition(QSlider.TicksBelow)
        
        # self.slider.setMinimum(0)
        # self.slider.setMaximum(255)
        self.slider.setRange(0, 255)
        self.slider.valueChanged.connect(self.changedValue)

        self.label = QLabel("Blue")
        self.label.setFont(QtGui.QFont("Sanserif", 15))
        self.label.setStyleSheet('QLabel { background: #0000FF; border-radius: 3px;}')

        hbox.addWidget(self.slider)
        hbox.addWidget(self.label)
        self.setLayout(hbox)

    def changedValue(self):
        size = self.slider.value()
        self.label.setText(str(size))

def main():
    app = QApplication(sys.argv)
    form = configForm()
    form.show()
    app.exec_()
    sys.exit()

if __name__ == "__main__":
    main()