# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_2022.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(646, 646)
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setEnabled(True)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 520, 645, 93))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 108))
        self.plainTextEdit.setSizeIncrement(QtCore.QSize(649, 108))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabConfig = QtWidgets.QTabWidget(self.centralwidget)
        self.tabConfig.setGeometry(QtCore.QRect(0, 0, 645, 523))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.tabConfig.setFont(font)
        self.tabConfig.setObjectName("tabConfig")
        self.imageTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.imageTab.setFont(font)
        self.imageTab.setObjectName("imageTab")
        self.image_grpbx = QtWidgets.QGroupBox(self.imageTab)
        self.image_grpbx.setGeometry(QtCore.QRect(9, 0, 184, 469))
        self.image_grpbx.setObjectName("image_grpbx")
        self.gridLayout = QtWidgets.QGridLayout(self.image_grpbx)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_image_brightness = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_brightness.setFont(font)
        self.lbl_image_brightness.setObjectName("lbl_image_brightness")
        self.gridLayout.addWidget(self.lbl_image_brightness, 0, 0, 1, 1)
        self.horSlider_image_birghtness = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_birghtness.setMaximum(255)
        self.horSlider_image_birghtness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_birghtness.setObjectName("horSlider_image_birghtness")
        self.gridLayout.addWidget(self.horSlider_image_birghtness, 0, 1, 1, 1)
        self.lbl_image_contrast = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_contrast.setFont(font)
        self.lbl_image_contrast.setObjectName("lbl_image_contrast")
        self.gridLayout.addWidget(self.lbl_image_contrast, 1, 0, 1, 1)
        self.horSlider_constrast = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_constrast.setMaximum(255)
        self.horSlider_constrast.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_constrast.setObjectName("horSlider_constrast")
        self.gridLayout.addWidget(self.horSlider_constrast, 1, 1, 1, 1)
        self.lbl_image_saturation = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_saturation.setFont(font)
        self.lbl_image_saturation.setObjectName("lbl_image_saturation")
        self.gridLayout.addWidget(self.lbl_image_saturation, 2, 0, 1, 1)
        self.horSlider_image_staturation = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_staturation.setMaximum(255)
        self.horSlider_image_staturation.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_staturation.setObjectName("horSlider_image_staturation")
        self.gridLayout.addWidget(self.horSlider_image_staturation, 2, 1, 1, 1)
        self.lbl_image_gain = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_gain.setFont(font)
        self.lbl_image_gain.setObjectName("lbl_image_gain")
        self.gridLayout.addWidget(self.lbl_image_gain, 3, 0, 1, 1)
        self.horSlider_image_gain = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_gain.setMaximum(255)
        self.horSlider_image_gain.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_gain.setObjectName("horSlider_image_gain")
        self.gridLayout.addWidget(self.horSlider_image_gain, 3, 1, 1, 1)
        self.lbl_image_exposure = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_exposure.setFont(font)
        self.lbl_image_exposure.setObjectName("lbl_image_exposure")
        self.gridLayout.addWidget(self.lbl_image_exposure, 4, 0, 1, 1)
        self.horSlider_image_exposure = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_exposure.setMaximum(255)
        self.horSlider_image_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_exposure.setObjectName("horSlider_image_exposure")
        self.gridLayout.addWidget(self.horSlider_image_exposure, 4, 1, 1, 1)
        self.lbl_image_sharpness = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_sharpness.setFont(font)
        self.lbl_image_sharpness.setObjectName("lbl_image_sharpness")
        self.gridLayout.addWidget(self.lbl_image_sharpness, 5, 0, 1, 1)
        self.horSlider_image_sharpness = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_sharpness.setMaximum(255)
        self.horSlider_image_sharpness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_sharpness.setObjectName("horSlider_image_sharpness")
        self.gridLayout.addWidget(self.horSlider_image_sharpness, 5, 1, 1, 1)
        self.lbl_image_gamma = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_gamma.setFont(font)
        self.lbl_image_gamma.setObjectName("lbl_image_gamma")
        self.gridLayout.addWidget(self.lbl_image_gamma, 6, 0, 1, 1)
        self.horSlider_image_gamma = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_gamma.setMaximum(255)
        self.horSlider_image_gamma.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_gamma.setObjectName("horSlider_image_gamma")
        self.gridLayout.addWidget(self.horSlider_image_gamma, 6, 1, 1, 1)
        self.lbl_image_temperature = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_temperature.setFont(font)
        self.lbl_image_temperature.setObjectName("lbl_image_temperature")
        self.gridLayout.addWidget(self.lbl_image_temperature, 7, 0, 1, 1)
        self.horSlider_image_temperature = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_temperature.setMaximum(255)
        self.horSlider_image_temperature.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_temperature.setObjectName("horSlider_image_temperature")
        self.gridLayout.addWidget(self.horSlider_image_temperature, 7, 1, 1, 1)
        self.lbl_image_focus = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_focus.setFont(font)
        self.lbl_image_focus.setObjectName("lbl_image_focus")
        self.gridLayout.addWidget(self.lbl_image_focus, 8, 0, 1, 1)
        self.horSlide_image_focus = QtWidgets.QSlider(self.image_grpbx)
        self.horSlide_image_focus.setMaximum(255)
        self.horSlide_image_focus.setOrientation(QtCore.Qt.Horizontal)
        self.horSlide_image_focus.setObjectName("horSlide_image_focus")
        self.gridLayout.addWidget(self.horSlide_image_focus, 8, 1, 1, 1)
        self.lbl_image_zoom = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_zoom.setFont(font)
        self.lbl_image_zoom.setObjectName("lbl_image_zoom")
        self.gridLayout.addWidget(self.lbl_image_zoom, 9, 0, 1, 1)
        self.horSlider_image_zoom = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_zoom.setMaximum(255)
        self.horSlider_image_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_zoom.setObjectName("horSlider_image_zoom")
        self.gridLayout.addWidget(self.horSlider_image_zoom, 9, 1, 1, 1)
        self.lbl_image_pan = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_pan.setFont(font)
        self.lbl_image_pan.setObjectName("lbl_image_pan")
        self.gridLayout.addWidget(self.lbl_image_pan, 10, 0, 1, 1)
        self.horSlider_image_pan = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_pan.setMaximum(255)
        self.horSlider_image_pan.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_pan.setObjectName("horSlider_image_pan")
        self.gridLayout.addWidget(self.horSlider_image_pan, 10, 1, 1, 1)
        self.lbl_image_tilt = QtWidgets.QLabel(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_tilt.setFont(font)
        self.lbl_image_tilt.setObjectName("lbl_image_tilt")
        self.gridLayout.addWidget(self.lbl_image_tilt, 11, 0, 1, 1)
        self.horSlider_image_tilt = QtWidgets.QSlider(self.image_grpbx)
        self.horSlider_image_tilt.setMaximum(255)
        self.horSlider_image_tilt.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_tilt.setObjectName("horSlider_image_tilt")
        self.gridLayout.addWidget(self.horSlider_image_tilt, 11, 1, 1, 1)
        self.ckb_image_mirror = QtWidgets.QCheckBox(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_mirror.setFont(font)
        self.ckb_image_mirror.setObjectName("ckb_image_mirror")
        self.gridLayout.addWidget(self.ckb_image_mirror, 12, 0, 1, 1)
        self.ckb_image_rotateup = QtWidgets.QCheckBox(self.image_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_rotateup.setFont(font)
        self.ckb_image_rotateup.setObjectName("ckb_image_rotateup")
        self.gridLayout.addWidget(self.ckb_image_rotateup, 12, 1, 1, 1)
        self.tabConfig.addTab(self.imageTab, "")
        self.videoTab = QtWidgets.QWidget()
        self.videoTab.setObjectName("videoTab")
        self.video_grpbx = QtWidgets.QGroupBox(self.videoTab)
        self.video_grpbx.setGeometry(QtCore.QRect(9, 0, 185, 277))
        self.video_grpbx.setObjectName("video_grpbx")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.video_grpbx)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckb_video_mirror = QtWidgets.QCheckBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_mirror.setFont(font)
        self.ckb_video_mirror.setObjectName("ckb_video_mirror")
        self.gridLayout_2.addWidget(self.ckb_video_mirror, 0, 0, 1, 1)
        self.ckb_video_invert = QtWidgets.QCheckBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_invert.setFont(font)
        self.ckb_video_invert.setObjectName("ckb_video_invert")
        self.gridLayout_2.addWidget(self.ckb_video_invert, 1, 0, 1, 1)
        self.ckb_video_blur = QtWidgets.QCheckBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_blur.setFont(font)
        self.ckb_video_blur.setObjectName("ckb_video_blur")
        self.gridLayout_2.addWidget(self.ckb_video_blur, 2, 0, 1, 1)
        self.ckb_video_mono = QtWidgets.QCheckBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_mono.setFont(font)
        self.ckb_video_mono.setObjectName("ckb_video_mono")
        self.gridLayout_2.addWidget(self.ckb_video_mono, 4, 0, 1, 1)
        self.cbb_video_framerate = QtWidgets.QComboBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_framerate.setFont(font)
        self.cbb_video_framerate.setCurrentText("")
        self.cbb_video_framerate.setObjectName("cbb_video_framerate")
        self.gridLayout_2.addWidget(self.cbb_video_framerate, 5, 0, 1, 1)
        self.cbb_video_resolution = QtWidgets.QComboBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_resolution.setFont(font)
        self.cbb_video_resolution.setObjectName("cbb_video_resolution")
        self.gridLayout_2.addWidget(self.cbb_video_resolution, 5, 1, 1, 1)
        self.ckb_video_rotateup = QtWidgets.QCheckBox(self.video_grpbx)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_rotateup.setFont(font)
        self.ckb_video_rotateup.setObjectName("ckb_video_rotateup")
        self.gridLayout_2.addWidget(self.ckb_video_rotateup, 3, 0, 1, 2)
        self.tabConfig.addTab(self.videoTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.imgLabel = QtWidgets.QLabel(self.logTab)
        self.imgLabel.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.imgLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imgLabel.setLineWidth(1)
        self.imgLabel.setText("")
        self.imgLabel.setTextFormat(QtCore.Qt.AutoText)
        self.imgLabel.setObjectName("imgLabel")
        self.tabConfig.addTab(self.logTab, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 646, 36))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")

        self.menuAction = QtWidgets.QMenu(self.menuBar)
        self.menuAction.setObjectName("menuAction")

        self.menuCamera = QtWidgets.QMenu(self.menuAction)
        self.menuCamera.setObjectName("menuCamera")

        self.menuDetect = QtWidgets.QMenu(self.menuAction)
        self.menuDetect.setObjectName("menuDetect")
        
        self.menuObject = QtWidgets.QMenu(self.menuDetect)
        self.menuObject.setObjectName("menuObject")

        self.menuRecognize = QtWidgets.QMenu(self.menuAction)
        self.menuRecognize.setObjectName("menuRecognize")
        
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")


        mainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionScan_Code = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.actionScan_Code.setFont(font)
        self.actionScan_Code.setObjectName("actionScan_Code")
        self.actionSave_profile = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_profile.setFont(font)
        self.actionSave_profile.setObjectName("actionSave_profile")
        self.actionConfigure = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionConfigure.setFont(font)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionLoad_profile = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionLoad_profile.setFont(font)
        self.actionLoad_profile.setObjectName("actionLoad_profile")
        self.actionExit = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionGet_Fps = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.actionGet_Fps.setFont(font)
        self.actionGet_Fps.setObjectName("actionGet_Fps")
        self.actionSave_Image = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Image.setFont(font)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionRestore_default_profile = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionRestore_default_profile.setFont(font)
        self.actionRestore_default_profile.setObjectName("actionRestore_default_profile")
        self.actionSave_Video = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Video.setFont(font)
        self.actionSave_Video.setObjectName("actionSave_Video")
        self.actionDetect_Object = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionDetect_Object.setFont(font)
        self.actionDetect_Object.setObjectName("actionDetect_Object")
        self.actionTake_photo = QtWidgets.QAction(mainWindow)
        self.actionTake_photo.setObjectName("actionTake_photo")
        self.actionRecord_Video = QtWidgets.QAction(mainWindow)
        self.actionRecord_Video.setObjectName("actionRecord_Video")
        self.actionColor = QtWidgets.QAction(mainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionQR_Code = QtWidgets.QAction(mainWindow)
        self.actionQR_Code.setObjectName("actionQR_Code")
        self.actionVegetables = QtWidgets.QAction(mainWindow)
        self.actionVegetables.setObjectName("actionVegetables")
        self.actionMask_No_Mask = QtWidgets.QAction(mainWindow)
        self.actionMask_No_Mask.setObjectName("actionMask_No_Mask")
        self.actionFace = QtWidgets.QAction(mainWindow)
        self.actionFace.setObjectName("actionFace")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_profile)
        self.menuFile.addAction(self.actionLoad_profile)
        self.menuFile.addAction(self.actionRestore_default_profile)
        self.menuFile.addAction(self.actionExit)
        self.menuCamera.addSeparator()
        self.menuCamera.addAction(self.actionTake_photo)
        self.menuCamera.addAction(self.actionRecord_Video)
        self.menuObject.addAction(self.actionVegetables)
        self.menuObject.addAction(self.actionMask_No_Mask)
        self.menuDetect.addAction(self.actionColor)
        self.menuDetect.addAction(self.menuObject.menuAction())
        self.menuDetect.addAction(self.actionQR_Code)
        self.menuRecognize.addAction(self.actionFace)
        self.menuAction.addAction(self.menuCamera.menuAction())
        self.menuAction.addAction(self.menuDetect.menuAction())
        self.menuAction.addAction(self.menuRecognize.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.tabConfig.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pixy Camera Control (2020)"))
        self.image_grpbx.setTitle(_translate("mainWindow", "Settings"))
        self.lbl_image_brightness.setText(_translate("mainWindow", "Brightness"))
        self.lbl_image_contrast.setText(_translate("mainWindow", "Contrast"))
        self.lbl_image_saturation.setText(_translate("mainWindow", "Saturation"))
        self.lbl_image_gain.setText(_translate("mainWindow", "Gain"))
        self.lbl_image_exposure.setText(_translate("mainWindow", "Exposure"))
        self.lbl_image_sharpness.setText(_translate("mainWindow", "Sharpness"))
        self.lbl_image_gamma.setText(_translate("mainWindow", "Gamma"))
        self.lbl_image_temperature.setText(_translate("mainWindow", "Temperature"))
        self.lbl_image_focus.setText(_translate("mainWindow", "Focus"))
        self.lbl_image_zoom.setText(_translate("mainWindow", "Zoom"))
        self.lbl_image_pan.setText(_translate("mainWindow", "Pan"))
        self.lbl_image_tilt.setText(_translate("mainWindow", "Tilt"))
        self.ckb_image_mirror.setText(_translate("mainWindow", "Mirror"))
        self.ckb_image_rotateup.setText(_translate("mainWindow", "Rotate up"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.imageTab), _translate("mainWindow", "Image control"))
        self.video_grpbx.setTitle(_translate("mainWindow", "Settings"))
        self.ckb_video_mirror.setText(_translate("mainWindow", "Mirror"))
        self.ckb_video_invert.setText(_translate("mainWindow", "Invert"))
        self.ckb_video_blur.setText(_translate("mainWindow", "Blur"))
        self.ckb_video_mono.setText(_translate("mainWindow", "Mono"))
        self.ckb_video_rotateup.setText(_translate("mainWindow", "Rotate up"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.videoTab), _translate("mainWindow", "Video control"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.logTab), _translate("mainWindow", "Logs"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuAction.setTitle(_translate("mainWindow", "Action"))
        self.menuCamera.setTitle(_translate("mainWindow", "Camera"))
        self.menuDetect.setTitle(_translate("mainWindow", "Detect"))
        self.menuObject.setTitle(_translate("mainWindow", "Object"))
        self.menuRecognize.setTitle(_translate("mainWindow", "Recognize"))

        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionHelp.setText(_translate("mainWindow", "Wiki"))
        self.actionAbout.setText(_translate("mainWindow", "About"))

        self.actionScan_Code.setText(_translate("mainWindow", "Scan code"))
        self.actionSave_profile.setText(_translate("mainWindow", "Save profile"))
        self.actionConfigure.setText(_translate("mainWindow", "Configure"))
        self.actionLoad_profile.setText(_translate("mainWindow", "Load profile"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionGet_Fps.setText(_translate("mainWindow", "Get FPS"))
        self.actionSave_Image.setText(_translate("mainWindow", "Save Image"))
        self.actionRestore_default_profile.setText(_translate("mainWindow", "Restore default profile"))
        self.actionRestore_default_profile.setIconText(_translate("mainWindow", "Restore default profile"))
        self.actionRestore_default_profile.setToolTip(_translate("mainWindow", "Restore default profile"))
        self.actionSave_Video.setText(_translate("mainWindow", "Save Video"))
        self.actionDetect_Object.setText(_translate("mainWindow", "Detect Object"))
        self.actionTake_photo.setText(_translate("mainWindow", "Take photo"))
        self.actionRecord_Video.setText(_translate("mainWindow", "Record video"))
        self.actionColor.setText(_translate("mainWindow", "Color"))
        self.actionQR_Code.setText(_translate("mainWindow", "QR Code"))
        self.actionVegetables.setText(_translate("mainWindow", "Vegetables"))
        self.actionMask_No_Mask.setText(_translate("mainWindow", "Mask/No Mask"))
        self.actionFace.setText(_translate("mainWindow", "Fontal Face"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

