# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_new.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(530, 541)
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabConfig = QtWidgets.QTabWidget(self.centralwidget)
        self.tabConfig.setGeometry(QtCore.QRect(0, 0, 527, 501))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.tabConfig.setFont(font)
        self.tabConfig.setObjectName("tabConfig")
        self.imageTab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.imageTab.setFont(font)
        self.imageTab.setObjectName("imageTab")
        self.image_grpbx = QtWidgets.QGroupBox(self.imageTab)
        self.image_grpbx.setGeometry(QtCore.QRect(10, -7, 511, 461))
        self.image_grpbx.setObjectName("image_grpbx")
        self.layoutWidget = QtWidgets.QWidget(self.image_grpbx)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 491, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horSlider_image_pan = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_pan.setMaximum(255)
        self.horSlider_image_pan.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_pan.setObjectName("horSlider_image_pan")
        self.gridLayout.addWidget(self.horSlider_image_pan, 9, 1, 1, 1)
        self.lbl_image_contrast = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_contrast.setFont(font)
        self.lbl_image_contrast.setObjectName("lbl_image_contrast")
        self.gridLayout.addWidget(self.lbl_image_contrast, 1, 0, 1, 1)
        self.horSlider_image_staturation = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_staturation.setMaximum(255)
        self.horSlider_image_staturation.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_staturation.setObjectName("horSlider_image_staturation")
        self.gridLayout.addWidget(self.horSlider_image_staturation, 2, 1, 1, 1)
        self.horSlider_image_sharpness = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_sharpness.setMaximum(255)
        self.horSlider_image_sharpness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_sharpness.setObjectName("horSlider_image_sharpness")
        self.gridLayout.addWidget(self.horSlider_image_sharpness, 5, 1, 1, 1)
        self.lbl_image_zoom = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_zoom.setFont(font)
        self.lbl_image_zoom.setObjectName("lbl_image_zoom")
        self.gridLayout.addWidget(self.lbl_image_zoom, 8, 0, 1, 1)
        self.horSlider_image_temperature = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_temperature.setMaximum(255)
        self.horSlider_image_temperature.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_temperature.setObjectName("horSlider_image_temperature")
        self.gridLayout.addWidget(self.horSlider_image_temperature, 6, 1, 1, 1)
        self.lbl_image_exposure = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_exposure.setFont(font)
        self.lbl_image_exposure.setObjectName("lbl_image_exposure")
        self.gridLayout.addWidget(self.lbl_image_exposure, 4, 0, 1, 1)
        self.lbl_image_focus = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_focus.setFont(font)
        self.lbl_image_focus.setObjectName("lbl_image_focus")
        self.gridLayout.addWidget(self.lbl_image_focus, 7, 0, 1, 1)
        self.horSlider_image_constrast = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_constrast.setMaximum(255)
        self.horSlider_image_constrast.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_constrast.setObjectName("horSlider_image_constrast")
        self.gridLayout.addWidget(self.horSlider_image_constrast, 1, 1, 1, 1)
        self.lbl_image_brightness = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_brightness.setFont(font)
        self.lbl_image_brightness.setObjectName("lbl_image_brightness")
        self.gridLayout.addWidget(self.lbl_image_brightness, 0, 0, 1, 1)
        self.lbl_image_pan = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_pan.setFont(font)
        self.lbl_image_pan.setObjectName("lbl_image_pan")
        self.gridLayout.addWidget(self.lbl_image_pan, 9, 0, 1, 1)
        self.horSlider_image_birghtness = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_birghtness.setMaximum(255)
        self.horSlider_image_birghtness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_birghtness.setObjectName("horSlider_image_birghtness")
        self.gridLayout.addWidget(self.horSlider_image_birghtness, 0, 1, 1, 1)
        self.horSlider_image_focus = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_focus.setMaximum(255)
        self.horSlider_image_focus.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_focus.setObjectName("horSlider_image_focus")
        self.gridLayout.addWidget(self.horSlider_image_focus, 7, 1, 1, 1)
        self.lbl_image_sharpness = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_sharpness.setFont(font)
        self.lbl_image_sharpness.setObjectName("lbl_image_sharpness")
        self.gridLayout.addWidget(self.lbl_image_sharpness, 5, 0, 1, 1)
        self.horSlider_image_gain = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_gain.setMaximum(255)
        self.horSlider_image_gain.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_gain.setObjectName("horSlider_image_gain")
        self.gridLayout.addWidget(self.horSlider_image_gain, 3, 1, 1, 1)
        self.lbl_image_gain = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_gain.setFont(font)
        self.lbl_image_gain.setObjectName("lbl_image_gain")
        self.gridLayout.addWidget(self.lbl_image_gain, 3, 0, 1, 1)
        self.lbl_image_temperature = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_temperature.setFont(font)
        self.lbl_image_temperature.setObjectName("lbl_image_temperature")
        self.gridLayout.addWidget(self.lbl_image_temperature, 6, 0, 1, 1)
        self.lbl_image_tilt = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_tilt.setFont(font)
        self.lbl_image_tilt.setObjectName("lbl_image_tilt")
        self.gridLayout.addWidget(self.lbl_image_tilt, 10, 0, 1, 1)
        self.horSlider_image_exposure = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_exposure.setMaximum(255)
        self.horSlider_image_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_exposure.setObjectName("horSlider_image_exposure")
        self.gridLayout.addWidget(self.horSlider_image_exposure, 4, 1, 1, 1)
        self.horSlider_image_zoom = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_zoom.setMaximum(255)
        self.horSlider_image_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_zoom.setObjectName("horSlider_image_zoom")
        self.gridLayout.addWidget(self.horSlider_image_zoom, 8, 1, 1, 1)
        self.horSlider_image_tilt = QtWidgets.QSlider(self.layoutWidget)
        self.horSlider_image_tilt.setMaximum(255)
        self.horSlider_image_tilt.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_tilt.setObjectName("horSlider_image_tilt")
        self.gridLayout.addWidget(self.horSlider_image_tilt, 10, 1, 1, 1)
        self.lbl_image_saturation = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_saturation.setFont(font)
        self.lbl_image_saturation.setObjectName("lbl_image_saturation")
        self.gridLayout.addWidget(self.lbl_image_saturation, 2, 0, 1, 1)
        self.ckb_image_rotateup = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_rotateup.setFont(font)
        self.ckb_image_rotateup.setObjectName("ckb_image_rotateup")
        self.gridLayout.addWidget(self.ckb_image_rotateup, 11, 1, 1, 1)
        self.ckb_image_mirror = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_mirror.setFont(font)
        self.ckb_image_mirror.setObjectName("ckb_image_mirror")
        self.gridLayout.addWidget(self.ckb_image_mirror, 11, 0, 1, 1)
        self.btn_capture = QtWidgets.QPushButton(self.image_grpbx)
        self.btn_capture.setGeometry(QtCore.QRect(10, 410, 491, 41))
        self.btn_capture.setObjectName("btn_capture")
        self.tabConfig.addTab(self.imageTab, "")
        self.videoTab = QtWidgets.QWidget()
        self.videoTab.setObjectName("videoTab")
        self.video_grpbx = QtWidgets.QGroupBox(self.videoTab)
        self.video_grpbx.setGeometry(QtCore.QRect(10, -7, 511, 471))
        self.video_grpbx.setObjectName("video_grpbx")
        self.cbb_video_framerate = QtWidgets.QComboBox(self.video_grpbx)
        self.cbb_video_framerate.setGeometry(QtCore.QRect(10, 260, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_framerate.setFont(font)
        self.cbb_video_framerate.setCurrentText("")
        self.cbb_video_framerate.setObjectName("cbb_video_framerate")
        self.cbb_video_resolution = QtWidgets.QComboBox(self.video_grpbx)
        self.cbb_video_resolution.setGeometry(QtCore.QRect(225, 260, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_resolution.setFont(font)
        self.cbb_video_resolution.setObjectName("cbb_video_resolution")
        self.layoutWidget1 = QtWidgets.QWidget(self.video_grpbx)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 171, 211))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckb_video_invert = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_invert.setFont(font)
        self.ckb_video_invert.setObjectName("ckb_video_invert")
        self.gridLayout_2.addWidget(self.ckb_video_invert, 1, 0, 1, 1)
        self.ckb_video_blur = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_blur.setFont(font)
        self.ckb_video_blur.setObjectName("ckb_video_blur")
        self.gridLayout_2.addWidget(self.ckb_video_blur, 2, 0, 1, 1)
        self.ckb_video_rotateup = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_rotateup.setFont(font)
        self.ckb_video_rotateup.setObjectName("ckb_video_rotateup")
        self.gridLayout_2.addWidget(self.ckb_video_rotateup, 3, 0, 1, 1)
        self.ckb_video_mono = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_mono.setFont(font)
        self.ckb_video_mono.setObjectName("ckb_video_mono")
        self.gridLayout_2.addWidget(self.ckb_video_mono, 4, 0, 1, 1)
        self.ckb_video_mirror = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_mirror.setFont(font)
        self.ckb_video_mirror.setObjectName("ckb_video_mirror")
        self.gridLayout_2.addWidget(self.ckb_video_mirror, 0, 0, 1, 1)
        self.btn_record = QtWidgets.QPushButton(self.video_grpbx)
        self.btn_record.setGeometry(QtCore.QRect(10, 410, 491, 41))
        self.btn_record.setObjectName("btn_record")
        self.tabConfig.addTab(self.videoTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.logTab)
        self.plainTextEdit.setGeometry(QtCore.QRect(-1, -1, 525, 461))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabConfig.addTab(self.logTab, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 530, 36))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menuBar)
        self.menuAction.setObjectName("menuAction")
        self.menuRecognize = QtWidgets.QMenu(self.menuAction)
        self.menuRecognize.setObjectName("menuRecognize")
        self.menuCamera = QtWidgets.QMenu(self.menuAction)
        self.menuCamera.setObjectName("menuCamera")
        self.menuDetect = QtWidgets.QMenu(self.menuAction)
        self.menuDetect.setObjectName("menuDetect")
        self.menuObject = QtWidgets.QMenu(self.menuDetect)
        self.menuObject.setObjectName("menuObject")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menuBar)
        self.actionHelp = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionHelp.setFont(font)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionScan_code = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.actionScan_code.setFont(font)
        self.actionScan_code.setObjectName("actionScan_code")
        self.actionDetect_color = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.actionDetect_color.setFont(font)
        self.actionDetect_color.setObjectName("actionDetect_color")
        self.actionSave_Pixy_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Pixy_parameters.setFont(font)
        self.actionSave_Pixy_parameters.setObjectName("actionSave_Pixy_parameters")
        self.actionConfigure = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionConfigure.setFont(font)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionLoad_Pixy_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionLoad_Pixy_parameters.setFont(font)
        self.actionLoad_Pixy_parameters.setObjectName("actionLoad_Pixy_parameters")
        self.actionExit = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Image = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Image.setFont(font)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionRestore_default_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionRestore_default_parameters.setFont(font)
        self.actionRestore_default_parameters.setObjectName("actionRestore_default_parameters")
        self.actionSave_Video = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Video.setFont(font)
        self.actionSave_Video.setObjectName("actionSave_Video")
        self.actionTake_Photo = QtWidgets.QAction(mainWindow)
        self.actionTake_Photo.setObjectName("actionTake_Photo")
        self.actionRecord_Video = QtWidgets.QAction(mainWindow)
        self.actionRecord_Video.setObjectName("actionRecord_Video")
        self.actionColor = QtWidgets.QAction(mainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionQR_Code = QtWidgets.QAction(mainWindow)
        self.actionQR_Code.setObjectName("actionQR_Code")
        self.actionMask_No_Mask = QtWidgets.QAction(mainWindow)
        self.actionMask_No_Mask.setObjectName("actionMask_No_Mask")
        self.actionVegetables = QtWidgets.QAction(mainWindow)
        self.actionVegetables.setObjectName("actionVegetables")
        self.actionFrontal_Face = QtWidgets.QAction(mainWindow)
        self.actionFrontal_Face.setObjectName("actionFrontal_Face")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConfigure)
        self.menuFile.addAction(self.actionSave_Pixy_parameters)
        self.menuFile.addAction(self.actionLoad_Pixy_parameters)
        self.menuFile.addAction(self.actionRestore_default_parameters)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_Video)
        self.menuFile.addAction(self.actionExit)
        self.menuRecognize.addAction(self.actionFrontal_Face)
        self.menuCamera.addAction(self.actionTake_Photo)
        self.menuCamera.addAction(self.actionRecord_Video)
        self.menuObject.addAction(self.actionMask_No_Mask)
        self.menuObject.addAction(self.actionVegetables)
        self.menuDetect.addAction(self.actionColor)
        self.menuDetect.addAction(self.menuObject.menuAction())
        self.menuDetect.addAction(self.actionQR_Code)
        self.menuAction.addAction(self.menuCamera.menuAction())
        self.menuAction.addAction(self.menuDetect.menuAction())
        self.menuAction.addAction(self.menuRecognize.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.tabConfig.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pixy Camera Control (2020)"))
        self.image_grpbx.setTitle(_translate("mainWindow", "Controls"))
        self.lbl_image_contrast.setText(_translate("mainWindow", "Contrast"))
        self.lbl_image_zoom.setText(_translate("mainWindow", "Zoom"))
        self.lbl_image_exposure.setText(_translate("mainWindow", "Exposure"))
        self.lbl_image_focus.setText(_translate("mainWindow", "Focus"))
        self.lbl_image_brightness.setText(_translate("mainWindow", "Brightness"))
        self.lbl_image_pan.setText(_translate("mainWindow", "Pan"))
        self.lbl_image_sharpness.setText(_translate("mainWindow", "Sharpness"))
        self.lbl_image_gain.setText(_translate("mainWindow", "Gain"))
        self.lbl_image_temperature.setText(_translate("mainWindow", "Temperature"))
        self.lbl_image_tilt.setText(_translate("mainWindow", "Tilt"))
        self.lbl_image_saturation.setText(_translate("mainWindow", "Saturation"))
        self.ckb_image_rotateup.setText(_translate("mainWindow", "Rotate up"))
        self.ckb_image_mirror.setText(_translate("mainWindow", "Mirror"))
        self.btn_capture.setText(_translate("mainWindow", "Capture"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.imageTab), _translate("mainWindow", "Image settings"))
        self.video_grpbx.setTitle(_translate("mainWindow", "Controls"))
        self.ckb_video_invert.setText(_translate("mainWindow", "Invert"))
        self.ckb_video_blur.setText(_translate("mainWindow", "Blur"))
        self.ckb_video_rotateup.setText(_translate("mainWindow", "Rotate up"))
        self.ckb_video_mono.setText(_translate("mainWindow", "Mono"))
        self.ckb_video_mirror.setText(_translate("mainWindow", "Mirror"))
        self.btn_record.setText(_translate("mainWindow", "Record"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.videoTab), _translate("mainWindow", "Video settings"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.logTab), _translate("mainWindow", "Logs"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuAction.setTitle(_translate("mainWindow", "Action"))
        self.menuRecognize.setTitle(_translate("mainWindow", "Recognize"))
        self.menuCamera.setTitle(_translate("mainWindow", "Camera"))
        self.menuDetect.setTitle(_translate("mainWindow", "Detect"))
        self.menuObject.setTitle(_translate("mainWindow", "Object"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionHelp.setText(_translate("mainWindow", "Wiki"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionScan_code.setText(_translate("mainWindow", "Scan QR code"))
        self.actionDetect_color.setText(_translate("mainWindow", "RGB color detect"))
        self.actionSave_Pixy_parameters.setText(_translate("mainWindow", "Save Pixy parameters"))
        self.actionConfigure.setText(_translate("mainWindow", "Configure"))
        self.actionLoad_Pixy_parameters.setText(_translate("mainWindow", "Load Pixy parameters"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionSave_Image.setText(_translate("mainWindow", "Save Image"))
        self.actionRestore_default_parameters.setText(_translate("mainWindow", "Restore default parameters"))
        self.actionSave_Video.setText(_translate("mainWindow", "Save Video"))
        self.actionTake_Photo.setText(_translate("mainWindow", "Take Photo"))
        self.actionRecord_Video.setText(_translate("mainWindow", "Record Video"))
        self.actionColor.setText(_translate("mainWindow", "Color"))
        self.actionQR_Code.setText(_translate("mainWindow", "QR Code"))
        self.actionMask_No_Mask.setText(_translate("mainWindow", "Mask/No Mask"))
        self.actionVegetables.setText(_translate("mainWindow", "Vegetables"))
        self.actionFrontal_Face.setText(_translate("mainWindow", "Frontal Face"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

