# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_new.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(531, 557)
        mainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image_grpbx = QtWidgets.QGroupBox(self.centralwidget)
        self.image_grpbx.setGeometry(QtCore.QRect(10, 10, 511, 451))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.image_grpbx.setFont(font)
        self.image_grpbx.setObjectName("image_grpbx")
        self.cbb_video_resolution = QtWidgets.QComboBox(self.image_grpbx)
        self.cbb_video_resolution.setGeometry(QtCore.QRect(360, 410, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_resolution.setFont(font)
        self.cbb_video_resolution.setObjectName("cbb_video_resolution")
        self.cbb_video_framerate = QtWidgets.QComboBox(self.image_grpbx)
        self.cbb_video_framerate.setGeometry(QtCore.QRect(10, 410, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.cbb_video_framerate.setFont(font)
        self.cbb_video_framerate.setCurrentText("")
        self.cbb_video_framerate.setObjectName("cbb_video_framerate")
        self.layoutWidget = QtWidgets.QWidget(self.image_grpbx)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 360, 491, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckb_image_mirror = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_mirror.setFont(font)
        self.ckb_image_mirror.setObjectName("ckb_image_mirror")
        self.gridLayout_2.addWidget(self.ckb_image_mirror, 0, 0, 1, 1)
        self.ckb_image_rotateup = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_image_rotateup.setFont(font)
        self.ckb_image_rotateup.setObjectName("ckb_image_rotateup")
        self.gridLayout_2.addWidget(self.ckb_image_rotateup, 0, 1, 1, 1)
        self.ckb_video_invert = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_invert.setFont(font)
        self.ckb_video_invert.setObjectName("ckb_video_invert")
        self.gridLayout_2.addWidget(self.ckb_video_invert, 0, 2, 1, 1)
        self.ckb_video_mono = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.ckb_video_mono.setFont(font)
        self.ckb_video_mono.setObjectName("ckb_video_mono")
        self.gridLayout_2.addWidget(self.ckb_video_mono, 0, 3, 1, 1)
        self.btn_record = QtWidgets.QPushButton(self.centralwidget)
        self.btn_record.setGeometry(QtCore.QRect(290, 470, 230, 41))
        self.btn_record.setObjectName("btn_record")
        self.btn_capture = QtWidgets.QPushButton(self.centralwidget)
        self.btn_capture.setGeometry(QtCore.QRect(10, 470, 230, 41))
        self.btn_capture.setObjectName("btn_capture")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 40, 491, 329))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_image_exposure = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_exposure.setFont(font)
        self.lbl_image_exposure.setObjectName("lbl_image_exposure")
        self.gridLayout.addWidget(self.lbl_image_exposure, 4, 0, 1, 1)
        self.horSlider_image_staturation = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_staturation.setMaximum(255)
        self.horSlider_image_staturation.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_staturation.setObjectName("horSlider_image_staturation")
        self.gridLayout.addWidget(self.horSlider_image_staturation, 2, 1, 1, 1)
        self.horSlider_image_sharpness = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_sharpness.setMaximum(255)
        self.horSlider_image_sharpness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_sharpness.setObjectName("horSlider_image_sharpness")
        self.gridLayout.addWidget(self.horSlider_image_sharpness, 5, 1, 1, 1)
        self.lbl_image_focus = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_focus.setFont(font)
        self.lbl_image_focus.setObjectName("lbl_image_focus")
        self.gridLayout.addWidget(self.lbl_image_focus, 6, 0, 1, 1)
        self.horSlider_image_gain = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_gain.setMaximum(255)
        self.horSlider_image_gain.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_gain.setObjectName("horSlider_image_gain")
        self.gridLayout.addWidget(self.horSlider_image_gain, 3, 1, 1, 1)
        self.horSlider_image_exposure = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_exposure.setMaximum(255)
        self.horSlider_image_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_exposure.setObjectName("horSlider_image_exposure")
        self.gridLayout.addWidget(self.horSlider_image_exposure, 4, 1, 1, 1)
        self.lbl_image_zoom = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_zoom.setFont(font)
        self.lbl_image_zoom.setObjectName("lbl_image_zoom")
        self.gridLayout.addWidget(self.lbl_image_zoom, 7, 0, 1, 1)
        self.lbl_image_sharpness = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_sharpness.setFont(font)
        self.lbl_image_sharpness.setObjectName("lbl_image_sharpness")
        self.gridLayout.addWidget(self.lbl_image_sharpness, 5, 0, 1, 1)
        self.lbl_image_contrast = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_contrast.setFont(font)
        self.lbl_image_contrast.setObjectName("lbl_image_contrast")
        self.gridLayout.addWidget(self.lbl_image_contrast, 1, 0, 1, 1)
        self.horSlider_image_zoom = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_zoom.setMaximum(255)
        self.horSlider_image_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_zoom.setObjectName("horSlider_image_zoom")
        self.gridLayout.addWidget(self.horSlider_image_zoom, 7, 1, 1, 1)
        self.lbl_image_gain = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_gain.setFont(font)
        self.lbl_image_gain.setObjectName("lbl_image_gain")
        self.gridLayout.addWidget(self.lbl_image_gain, 3, 0, 1, 1)
        self.horSlider_image_focus = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_focus.setMaximum(255)
        self.horSlider_image_focus.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_focus.setObjectName("horSlider_image_focus")
        self.gridLayout.addWidget(self.horSlider_image_focus, 6, 1, 1, 1)
        self.lbl_image_brightness = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_image_brightness.setFont(font)
        self.lbl_image_brightness.setObjectName("lbl_image_brightness")
        self.gridLayout.addWidget(self.lbl_image_brightness, 0, 0, 1, 1)
        self.lbl_image_saturation = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_saturation.setFont(font)
        self.lbl_image_saturation.setObjectName("lbl_image_saturation")
        self.gridLayout.addWidget(self.lbl_image_saturation, 2, 0, 1, 1)
        self.horSlider_image_birghtness = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_birghtness.setMaximum(255)
        self.horSlider_image_birghtness.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_birghtness.setObjectName("horSlider_image_birghtness")
        self.gridLayout.addWidget(self.horSlider_image_birghtness, 0, 1, 1, 1)
        self.horSlider_image_constrast = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_constrast.setMaximum(255)
        self.horSlider_image_constrast.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_constrast.setObjectName("horSlider_image_constrast")
        self.gridLayout.addWidget(self.horSlider_image_constrast, 1, 1, 1, 1)
        self.lbl_image_blur = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_image_blur.setFont(font)
        self.lbl_image_blur.setObjectName("lbl_image_blur")
        self.gridLayout.addWidget(self.lbl_image_blur, 8, 0, 1, 1)
        self.horSlider_image_blur = QtWidgets.QSlider(self.layoutWidget_3)
        self.horSlider_image_blur.setMaximum(255)
        self.horSlider_image_blur.setOrientation(QtCore.Qt.Horizontal)
        self.horSlider_image_blur.setObjectName("horSlider_image_blur")
        self.gridLayout.addWidget(self.horSlider_image_blur, 8, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 531, 36))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAction = QtWidgets.QMenu(self.menuBar)
        self.menuAction.setObjectName("menuAction")
        self.menuRecognize = QtWidgets.QMenu(self.menuAction)
        self.menuRecognize.setObjectName("menuRecognize")
        self.menuCamera = QtWidgets.QMenu(self.menuAction)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.menuCamera.setFont(font)
        self.menuCamera.setObjectName("menuCamera")
        self.menuDetect = QtWidgets.QMenu(self.menuAction)
        self.menuDetect.setObjectName("menuDetect")
        self.menuObject = QtWidgets.QMenu(self.menuDetect)
        self.menuObject.setObjectName("menuObject")
        self.menuIncrease = QtWidgets.QMenu(self.menuAction)
        self.menuIncrease.setObjectName("menuIncrease")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.menuBar)
        self.actionWiki = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionWiki.setFont(font)
        self.actionWiki.setObjectName("actionWiki")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQR_Code = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionQR_Code.setFont(font)
        self.actionQR_Code.setObjectName("actionQR_Code")
        self.actionColor = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionColor.setFont(font)
        self.actionColor.setObjectName("actionColor")
        self.actionSave_Pixy_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Pixy_parameters.setFont(font)
        self.actionSave_Pixy_parameters.setObjectName("actionSave_Pixy_parameters")
        self.actionConfigure = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionConfigure.setFont(font)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionLoad_Pixy_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionLoad_Pixy_parameters.setFont(font)
        self.actionLoad_Pixy_parameters.setObjectName("actionLoad_Pixy_parameters")
        self.actionExit = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Image = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Image.setFont(font)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionRestore_default_parameters = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionRestore_default_parameters.setFont(font)
        self.actionRestore_default_parameters.setObjectName("actionRestore_default_parameters")
        self.actionSave_Video = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionSave_Video.setFont(font)
        self.actionSave_Video.setObjectName("actionSave_Video")
        self.actionTake_Photo = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionTake_Photo.setFont(font)
        self.actionTake_Photo.setObjectName("actionTake_Photo")
        self.actionRecord_Video = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionRecord_Video.setFont(font)
        self.actionRecord_Video.setObjectName("actionRecord_Video")
        self.actionColor1 = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionColor1.setFont(font)
        self.actionColor1.setObjectName("actionColor1")
        self.actionQR_Code1 = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionQR_Code1.setFont(font)
        self.actionQR_Code1.setObjectName("actionQR_Code1")
        self.actionMask_No_Mask = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionMask_No_Mask.setFont(font)
        self.actionMask_No_Mask.setObjectName("actionMask_No_Mask")
        self.actionVegetables = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionVegetables.setFont(font)
        self.actionVegetables.setObjectName("actionVegetables")
        self.actionFrontal_Face = QtWidgets.QAction(mainWindow)
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(11)
        self.actionFrontal_Face.setFont(font)
        self.actionFrontal_Face.setObjectName("actionFrontal_Face")
        self.actionFPS = QtWidgets.QAction(mainWindow)
        self.actionFPS.setObjectName("actionFPS")
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionConfigure)
        self.menuFile.addAction(self.actionSave_Pixy_parameters)
        self.menuFile.addAction(self.actionLoad_Pixy_parameters)
        self.menuFile.addAction(self.actionRestore_default_parameters)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_Video)
        self.menuFile.addAction(self.actionExit)
        self.menuRecognize.addAction(self.actionFrontal_Face)
        self.menuCamera.addAction(self.actionTake_Photo)
        self.menuCamera.addAction(self.actionRecord_Video)
        self.menuObject.addAction(self.actionMask_No_Mask)
        self.menuObject.addAction(self.actionVegetables)
        self.menuDetect.addAction(self.actionColor)
        self.menuDetect.addAction(self.menuObject.menuAction())
        self.menuDetect.addAction(self.actionQR_Code)
        self.menuIncrease.addAction(self.actionFPS)
        self.menuAction.addAction(self.menuCamera.menuAction())
        self.menuAction.addAction(self.menuDetect.menuAction())
        self.menuAction.addAction(self.menuRecognize.menuAction())
        self.menuAction.addAction(self.menuIncrease.menuAction())
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAction.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pixy Camera Control (2020)"))
        self.image_grpbx.setTitle(_translate("mainWindow", "Photo/Video Settings"))
        self.ckb_image_mirror.setText(_translate("mainWindow", "Mirror"))
        self.ckb_image_rotateup.setText(_translate("mainWindow", "Rotate up"))
        self.ckb_video_invert.setText(_translate("mainWindow", "Invert"))
        self.ckb_video_mono.setText(_translate("mainWindow", "Mono"))
        self.btn_record.setText(_translate("mainWindow", "Record"))
        self.btn_capture.setText(_translate("mainWindow", "Capture"))
        self.lbl_image_exposure.setText(_translate("mainWindow", "Exposure"))
        self.lbl_image_focus.setText(_translate("mainWindow", "Focus"))
        self.lbl_image_zoom.setText(_translate("mainWindow", "Zoom"))
        self.lbl_image_sharpness.setText(_translate("mainWindow", "Sharpness"))
        self.lbl_image_contrast.setText(_translate("mainWindow", "Contrast"))
        self.lbl_image_gain.setText(_translate("mainWindow", "Gain"))
        self.lbl_image_brightness.setText(_translate("mainWindow", "Brightness"))
        self.lbl_image_saturation.setText(_translate("mainWindow", "Saturation"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuAction.setTitle(_translate("mainWindow", "Action"))
        self.menuRecognize.setTitle(_translate("mainWindow", "Recognize"))
        self.menuCamera.setTitle(_translate("mainWindow", "Camera"))
        self.menuDetect.setTitle(_translate("mainWindow", "Detect"))
        self.menuObject.setTitle(_translate("mainWindow", "Object"))
        self.menuIncrease.setTitle(_translate("mainWindow", "Increase"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.actionWiki.setText(_translate("mainWindow", "Wiki"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionQR_Code.setText(_translate("mainWindow", "QR code"))
        self.actionColor.setText(_translate("mainWindow", "Color"))
        self.actionSave_Pixy_parameters.setText(_translate("mainWindow", "Save Pixy parameters"))
        self.actionConfigure.setText(_translate("mainWindow", "Configure"))
        self.actionLoad_Pixy_parameters.setText(_translate("mainWindow", "Load Pixy parameters"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionSave_Image.setText(_translate("mainWindow", "Save Image"))
        self.actionRestore_default_parameters.setText(_translate("mainWindow", "Restore default parameters"))
        self.actionSave_Video.setText(_translate("mainWindow", "Save Video"))
        self.actionTake_Photo.setText(_translate("mainWindow", "Take Photo"))
        self.actionRecord_Video.setText(_translate("mainWindow", "Record Video"))
        self.actionColor1.setText(_translate("mainWindow", "Color"))
        self.actionQR_Code1.setText(_translate("mainWindow", "QR Code"))
        self.actionMask_No_Mask.setText(_translate("mainWindow", "Mask/No Mask"))
        self.actionVegetables.setText(_translate("mainWindow", "Vegetables"))
        self.actionFrontal_Face.setText(_translate("mainWindow", "Frontal Face"))
        self.actionFPS.setText(_translate("mainWindow", "FPS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

